[package]
name = "risp_macro"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["myyrakle <sssang97@naver.com>"] 
description = "LISP" 
keywords = ["lisp", "functional"] 
repository = "https://github.com/myyrakle/common_risp" 

[dependencies]

[lib]
proc-macro=true